config/routes.rb
Rails.application.routes.draw do
  resources :autors
  # resources :books
  resources :purchases
  root to: 'users#display_login_form'
  get '/login', to: 'users#display_login_form'
  post '/users/authenticate', to: 'users#authenticate'
  get '/users/new', to: 'users#new'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show'
  get '/books/new', to: 'books#new'
  # post '/books', to: 'books#add'
  get '/books', to: 'books#index'
  get '/books/search',to:'books#search'
  post '/books/create' , to: 'books#create'
  get '/books/:id', to: 'books#show'
  delete '/users', to: 'users#destroy'
  get '/users/:id/edit', to: 'users#edit'
  patch 'users/:id',to: 'users#update'
  post '/books' ,to: 'books#search_form'
  delete '/books/:id', to: 'books#destroy'

  

  # post '/users/' ,to: 'users#create'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/autor.rb
class Autor < ApplicationRecord
   
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :purchases
    has_many :users, through: :purchases
    
    

    

end

app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :book
    belongs_to :user

    
end

app/models/user.rb
class User < ApplicationRecord
   
    has_many :purchases
    has_many :books, through: :purchases
    has_one_attached :avatar 
    has_secure_password
    validates :user_name, uniqueness:{case_sensitive:false}

    
    def before_save
        self.user_name.capitalize!
    end
        
    def add_book(book_id)
        item = items.where('book_id = ?', book_id).first
    if item
        # increase the quantity of product in cart
        item.quantity + 1
        save
    else
        # product does not exist in cart
        book= Book.find(book_id)
        items << book
    end

    
    
end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :current_user

    def current_user
       @current_user = User.find(session[:user_id])
    end
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # helper_method :api_image_search
  
  def create
      book = Book.create(strong_params)
      user_id = session[:user_id]
      Purchase.create(user_id: user_id, book_id: book.id)
      redirect_to "/users/#{user_id}"
  end


  def index
      @books = Book.all
      id=session[:user_id]
      @user= User.find(id)
  end
  def show
    @book = Book.find(params[:id])
  end

  def search
      @search = @@search_result
  end

  def search_form
    if strong_params[:book_list] == 'author'
       @@search_result = api_search("author:#{strong_params[:search]}")
       redirect_to "/books/search"
    elsif strong_params[:book_list] == 'title'
      @@search_result = api_search(strong_params[:search])
      redirect_to "/books/search"
    end
  end

  def api_search(input)
    response = RestClient.get("https://www.googleapis.com/books/v1/volumes?q=#{input}&printType=books")
    api_response = JSON.parse(response)
    api_response
  end

  def api_image_search
    img_url = nil
    @@search_result['items'].each do |book|
      self_link = RestClient.get(book['selfLink'])
      img_url = self_link['volumeInfo']['imageLinks']['small']  
    end
      img_url
  end

  

    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to "/books"
    end
  



    def strong_params
     
    params.require(:book).permit([:title, :genre, :img_url, :author, :book_list, :search, :summary, :page_count])

  end


end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    def create 
        user_id=session[:user_id]
        
        Purchase.create(book_id: params[:book_id], user_id: user_id)

        redirect_to "/users/#{user_id}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users= User.all
        @book=Book.all
    end

    def show
        @user = User.find(params[:id])
       
        
    end

    def display_login_form
        if flash[:error]
            @error = flash[:error]
        end 
    end
    
    def new 
        if flash[:error]
            @error = flash[:error]
        else
            @error = {"user_name" => []}
        end
    end

    def create
        user = User.new(strong_params)
        if user.valid?
            user.before_save
            user.save
            redirect_to  "/login"
        else
            flash[:error] = user.errors.messages
            redirect_to "/users/new"
        end
    end

    def edit
        @user =User.find(params[:id])
    end

    def update
     user = User.find(params[:id])
     user.update(strong_params)
     redirect_to "/users/#{user.id}"  
    end

    def authenticate
        user = User.find_by(user_name: params[:user_name].capitalize)           # The username the use wrote to find the user
        if user != nil && user.authenticate(params[:password] )                 # Then check if the password they wrote was correct
             # If it was, save the users id in the session
            session[:user_id] = user.id
            redirect_to "/users/#{user.id}"
        else 
            flash[:error] = "Username/Password not found"                       #assigns 'error message' to flash cookie
            redirect_to "/login"
        end
    end



    def destroy

        session[:user_id] = nil     
        redirect_to '/login' 
    end

    

    

    def strong_params

    
        params.require(:user).permit([:user_name, :password])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.erb
<head>
<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .btn btn-primary btn-sm{
        font-size: 100px;
      }
    </style>
    <!-- Custom styles for this template -->
    
</head>
<body >
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/users/<%=@user.id%>">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <%= link_to "Logout", "/users", method: "delete", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        
        <form class="form-inline mt-2 mt-md-0" id='search' action="/books" accept-charset="UTF-8" data-remote="true" method="post">
         
         <select name="book[book_list]" form="search" class='form-control' style='margin:.5em'>
          <option name="book[author]" value="author" class='form-control'>Author</option>
          <option name= "book[title]" value="title" class='form-control'>Title</option>
        </select>
        
        
        <input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="authenticity_token" value="1kXru2KnjDv03DklG9bdCmbqYh6l+IJSDQgIGZrfEP7n0wziyV3nv2zs+IFgm6m7fkjMyMpHUtaQi1Nm1M2ICA==" class="form-signin container">
          <br>
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search"  name='book[search]'>
          <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

  

<main role="main" >
  
  

  <div class="album py-5 " style='background-color:Darkgrey'>
  <br>
  <br>
    <div class="text-center" style="margin:0em"> 
        <h1 style=" color:Black; font-size: 65px; font-family: 'Times New Roman';font-weight: 'bold' ">Welcome to The BookHub</h1>
    </div>
    <br>
    <div class="container">

      <div class="row">
      <% @books.each do |book| %>  
           
        <div class="col-md-4 container jumbotron">
          <div class="card mb-3 shadow-sm ">
            <a href = <%="/books/#{book.id}"%>>
            <img class="bd-placeholder-img card-img-top" width="200" height="225" src=<%="#{book.img_url}"%> >
            </a>

            <div class="card-body">
              <p style="  font-size: 20px; font-family: bold;font-style: italic;" class="card-text">Title: <%= book.title %></p>
              <p style="  font-size: 20px; font-family: bold;font-style: italic;"class="card-text">Category: <%= book.genre %></p>
              <p style="  font-size: 20px; font-family: bold;font-style: italic;"class="card-text">Author: <%= book.author%></p>
              <div class="d-flex justify-content-between align-items-center">
                <div >
                  <%= button_to "Purchase", purchases_path(book_id: book.id, :method => :post), class:"btn btn-primary btn-sm"%> <!--Button Helper post to purchases/create passes book.id in params>-->
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<%=%>
</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.3/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
</body>

app/views/books/new.erb
<%= form_with model: @book do |f| %>
  Title: <%= f.text_field :title %>
  Genre: <%= f.text_field :genre %>

  
  autor_id<%= f.collection_select :autor_id, Autor.all,:id,:name %>

  <%= f.submit "Create New Book" %>


  

<% end %>

app/views/books/search.erb
<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    
  </head>
  <body>
    <header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">asdfadf</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm fixed-top">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <a href="/books" class="btn btn-secondary my-2">Book Home Page</a>
    </div>
  </div>
</header>

<main role="main" >


  <div class="album py-5" style='background-color:Darkgrey'>
      <br>
      <br>
      <div class="text-center" style="margin:0em"> 
        <h1 style=" color:Black; font-size: 65px; font-family: 'Times New Roman';font-weight: 'bold' ">Welcome to The BookHub Search</h1>
      </div>
    <div class="container">
      <div class="row">
       <%@search['items'].each do |book|%> 


        
      
      
        <%self_link = RestClient.get(book['selfLink'])%>
        <%item_info = JSON.parse(self_link)%>
        <%img_url = item_info['volumeInfo']['imageLinks']['small'] %>
      
    
           
        <div class="col-md-4 container jumbotron">
          <div class="card mb-3 shadow-sm ">
            
            <img class="bd-placeholder-img card-img-top" width="200" height="225" src=<%=img_url%> >
            </a>

            <div class="card-body">
              <p class="card-text">Title: <%= book['volumeInfo']['title']%></p>
              <p class="card-text">Category: <%= book['volumeInfo']['categories'][0]%> </p>
              <p class="card-text">Author: <%= book['volumeInfo']['authors'][0]%></p>
              <div class="d-flex justify-content-between align-items-center">
                <div >
                  <%= button_to "Purchase", {:controller => "books", :action => "create", :book => {:title => book['volumeInfo']['title'], :author => book['volumeInfo']['authors'][0], :genre => book['volumeInfo']['categories'][0], :img_url => img_url, :page_count => book['volumeInfo']['pageCount'], :summary => book['volumeInfo']['description']}}, :method=> :post, class:"btn btn-primary btn-sm"%> 
                 
                 
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.3/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>





    

app/views/books/show.erb
<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    
  </head>
  <body>
    <header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">asdfadf</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <a href="/books" class="btn btn-secondary my-2">BookHomePage</a>
    </div>
  </div>
</header>

<main role="main">

  <div class="album py-5" style="background-color:Lightgrey">
    <div class="container">

      <div class="row">
      
        
        
        <div class="col">
          <div class="card mb-4 shadow-sm">
            
            <img class="bd-placeholder-img card-img-top" height="550" src=<%="#{@book.img_url}"%> preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="20%" height="50%" fill="#55595c"/>
        
            <div class="card-body shadow-sm">
              <h4><%=@book.title%> </h4>
              <div class="d-flex justify-content-between align-items-center">
               
                <div >
                  <%= button_to "Purchase", purchases_path(book_id: @book.id, :method => :post), class:"btn btn-primary btn-sm"%> <!--Button Helper post to purchases/create passes book.id in params>-->
                </div>
                <div>
                <%= link_to 'Delete', "/books/#{@book.id}", method: "DELETE", class:'btn btn-danger btn-sm' %>

                </div>
                
              </div>
            </div>
          </div>
        </div>
        <div class= 'col'>
          <br>
          <br>
          <br>
          <p><strong>Category: </strong><%= @book.genre %></p>
          <p><strong>Author: </strong><%= @book.author %></p>
          <p><strong>Pages: </strong><%= @book.page_count %></p>
          <p> <strong>Summary: </strong> <%= @book.summary %> </p>
        </div>
    
      </div>
    </div>
  </div>

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.3/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksInformation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
   
  </body>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
</html>

app/views/purchases/new.erb
<%= form_with model: @purchase do |f| %>
  
  
  book_id<%= f.collection_select :book_id, Book.all,:id,:name %>

  <%= f.submit "Purchase" %>



  

<% end %>

app/views/users/display_login_form.erb
  <head>
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    
  </head>
  <body class="text-center jumbotron container" style='background-image: linear-gradient(to top, #30cfd0 0%, #330867 100%);'>
  
  <div class= 'container' style='width:400px'>
  <form action="/users/authenticate" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="1kXru2KnjDv03DklG9bdCmbqYh6l+IJSDQgIGZrfEP7n0wziyV3nv2zs+IFgm6m7fkjMyMpHUtaQi1Nm1M2ICA==" class="form-signin container">
    <br>
    <br>
    <br>
    <br>

    <h1 class="h3 mb-3 font-weight-normal" style=" color:white; font-size: 46px; font-family:'Times New Roman';font-weight: bold;" >Login</h1>
      <label for="inputUsername" class="sr-only">Username</label>
      <input type="text" name="user_name" id="user_name" class="form-control form-control-lg" placeholder="Username" required onfocus="this.value=" value="" style= 'text-transform: capitalize'>
      <p style='color:Red'><%=@error%> </p>   <!--  error message on wrong/unknown username/password -->
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password" id="password" class="form-control form-control-lg" placeholder="Password"  onfocus="this.value=''" value="" required >
      <br>
      <div class= 'container text-center' style='width:150px'>
      <button class="btn btn-md btn-primary btn-block" type="submit" name="commit" style='background-color:Darkblue'>Sign in</button>
      <div>
  </form>
</div>
</body>


<div>
<br>
  
  <a class='' href="/users/new"><button class="btn btn-md btn-primary btn-block" style='background-color:green' >Sign up?</button></a>
</div>
     
<p class="mt-5 mb-3 text-muted">&copy; 2019-2020</p>

app/views/users/edit.erb
<!--<%= form_with scope: :user, method: "patch" ,url: "/users/#{@user.id}" do |f| %>
  <div>
  Username: <%= f.text_field :user_name %>
  </div>
  <div>
  Password: <%= f.password_field :password %>
  </div>
  <%= f.submit "edit" %>
  

  

<% end %> 
-->



<head>
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    
  </head>
  <body class="text-center jumbotron container" style='background-image: linear-gradient(to top, #30cfd0 0%, #330867 100%);'>
  <div class= 'container' style='width:400px'>
      <form action="/users/<%=@user.id%>" accept-charset="UTF-8" data-remote="true" method="post">
        <input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="_method" value="patch">
        <input type="hidden" name="authenticity_token" value="1kXru2KnjDv03DklG9bdCmbqYh6l+IJSDQgIGZrfEP7n0wziyV3nv2zs+IFgm6m7fkjMyMpHUtaQi1Nm1M2ICA==" class="form-signin container">
        <br>
        <br>
        <br>
        <br>
        <h1 class="h3 mb-3 font-weight-normal" style=" color:white; font-size: 46px; font-family:'Times New Roman';font-weight: bold;" >Please Edit Your Information</h1>
        <br>
        <br>
        <br>
        <br>
        <label for="inputUsername" class="sr-only">Username</label>
        <input type="text" name="user[user_name]" id="user_name" class="form-control form-control-lg" placeholder="<%=@user.user_name%>" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="user[password]" id="password" class="form-control form-control-lg" placeholder="Password" required>
        
        
        <div class= 'container text-center' style='width:150px'>
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit" name="commit" style='background-color:Darkblue'>Edit</button>
        <%= link_to 'Cancel', "/users/#{@user.id}", class: "btn btn-lg btn-danger btn-block" %>
        </div>
        <p class="mt-5 mb-3 text-muted">&copy; 2019-2020</p>
      </form>
    </div>
</body>

 











  



 
  

app/views/users/new.erb
 
<head>
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    
  </head>
  <body class="text-center jumbotron container" style='background-image: linear-gradient(to top, #30cfd0 0%, #330867 100%);'>
    <div class='container-fluid' style='width:400px'>
    <form action="/users" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="EZ3MQY9qlImPoURFIc1Ob9Ha3V2BAVUVum4Rfazv4KYvbjOVgbS/S1fegxGPgC+5BJVRFtyYl7PE0Mlb4QJ2Nw==" class="form-signin container">
      
      <h1 class="h3 mb-3 font-weight-normal" style='color:white'>Sign Up</h1>
      <br>
      <br>
      <br>
      <label for="inputUsername" class="sr-only">Username</label>
      <input type="text" name="user[user_name]" id="user_user_name" class="form-control form-control-lg" placeholder="Username" required autofocus style= 'text-transform: capitalize'>
       <% @error['user_name'].each do |message|%>
        <p style='color:red'> <%= message %> </p>
      <%end%>
      <br>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="user[password]" id="user_password" class="form-control form-control-lg" placeholder="Password" required>
      <div class= 'container text-center' style='width:150px'>
      <br>
      <button class="btn btn-md btn-primary btn-block" type="submit" name="commit" style='background-color:Darkblue'>Sign Up</button>
      <br>
      <%= link_to 'Cancel', '/login', class: "btn btn-md btn-danger btn-block" %>
      <p class="mt-5 mb-3 text-muted">&copy; 2019-2020</p>
      </div>
    </form>
   
   </div> 
</body>